---
- name: Add custom decoders
  blockinfile:
    marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
    block: "{{ lookup('file', 'local_decoder.xml') }}"
    path: /var/ossec/etc/decoders/local_decoder.xml

- name: Add custom rules
  blockinfile:
    marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
    block: "{{ lookup('file', 'local_rules.xml') }}"
    path: /var/ossec/etc/rules/local_rules.xml

- name: Restart wazuh-manager
  service:
    name: wazuh-manager
    state: restarted
    enabled: true
