---
elastic_host: elastic.service.consul
es_volume: es_data
service_config_dir: /etc/elk/
provisioner_configs_dir: "{{ playbook_dir }}/../../config/"

images:
  elasticsearch: "docker.elastic.co/elasticsearch/elasticsearch"
  kibana: "docker.elastic.co/kibana/kibana"
  logstash: "docker.elastic.co/logstash/logstash"

  consul: consul:1.0.0
  registrator: gliderlabs/registrator:v6

ips:
  logstash: 192.168.55.10

ports:
  kibana: 5601
  elasticsearch: 9200
  logstash: 5044
