---
- import_tasks: facts/common.yml
- import_tasks: facts/container.yml

- name: Check if {{ service_name_altered }} already running
  command: docker inspect {{ service_name_altered }}
  register: service_running
  ignore_errors: true

- meta: end_play
  when: no_restart is defined and no_restart and not force_restart and service_running is succeeded and service_running.stdout == 'running'

- name: If {{ service_name_altered }} already running, remove it
  command: docker rm -f {{ service_name_altered }}
  when: service_running is succeeded

- name: Run service {{ service_name_altered }}  {{ start_args }}
  command: docker run -d {{ start_args }}
  when: run_to_completion is undefined or run_to_completion is defined and not run_to_completion

- name: Run and check result {{ service_name_altered }}
  command: docker run --rm {{ start_args }}
  register: service_run_result
  when: run_to_completion is defined and run_to_completion
