---
- import_tasks: facts/common.yml
- import_tasks: facts/container.yml

- name: Check if {{ service_name_altered }} already running
  command: docker inspect {{ service_name_altered }}
  register: service_running
  ignore_errors: true

- meta: end_play
  when: no_restart is defined and no_restart and not force_restart and service_running is succeeded and service_running.stdout == 'running'

- name: If {{ service_name_altered }} already running, remove it
  command: docker rm -f {{ service_name_altered }}
  when: service_running is succeeded

- name: Add systemd unit for {{ service_name_altered }}
  template:
    src: "systemd.service.j2"
    dest: "/etc/systemd/system/docker-{{ service_name_altered }}.service"
    owner: root
    group: root
    mode: 0644
  register: docker_unit


- name: Start systemd service {{ service_name_altered }}
  systemd: "name=docker-{{ service_name_altered }} state=started enabled=yes daemon_reload=yes"
  when: (docker_unit|changed)

# - name: Restart systemd service {{ service_name_altered }}
#  systemd: "name=docker-{{ service_name_altered }} state=restarted enabled=yes daemon_reload=yes"
#  when: (docker_unit|changed)

- name: explictly enable ip forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: yes
    state: present
    reload: yes
