# -*- mode: ruby -*-
# vi: set ft=ruby :

servers=[
  {
    :hostname => "manager",
    :ip => "192.168.33.10",
    :box => "centos/7",
    :ram => 4096,
    :cpu => 2
  },  
  {
    :hostname => "agent1",
    :ip => "192.168.33.11",
    :box => "centos/7",
    :ram => 512,
    :cpu => 1
  },
  {
    :hostname => "agent2",
    :ip => "192.168.33.12",
    :box => "centos/7",
    :ram => 512,
    :cpu => 1
  }
]

Vagrant.configure(2) do |config|
  servers.each do |machine|
      config.vm.define machine[:hostname] do |node|
          if machine[:hostname] == "manager"
            node.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "192.168.33.10"
            node.vm.network "forwarded_port", guest: 443, host: 8443 , host_ip: "192.168.33.10"
            node.vm.network "forwarded_port", guest: 55000, host: 55000 , host_ip: "192.168.33.10"
            node.vm.network "forwarded_port", guest: 1514, host: 1514 , host_ip: "192.168.33.10"
            node.vm.network "forwarded_port", guest: 1515, host: 1515 , host_ip: "192.168.33.10"
            node.vm.network "forwarded_port", guest: 1516, host: 1516 , host_ip: "192.168.33.10"
          end
          node.vm.box = machine[:box]
          node.vm.hostname = machine[:hostname]
          node.vm.network "private_network", ip: machine[:ip]
          node.vm.provider "virtualbox" do |vb|
            vb.customize ["modifyvm", :id, "--memory", machine[:ram]]
          end
      end
  end
end