---
- name: Set provisioner_configs_dir variable if not
  set_fact:
    provisioner_configs_dir: "{{ playbook_dir }}/../config/"
  when: provisioner_configs_dir is not defined

- name: create config dirs
  become: yes
  file:
    path: "{{ service_config_dir }}/{{ service_name_altered }}/{{ (one_config_definition.dst_path | default(one_config_definition.path | default(one_config_definition.src_path))) | dirname }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items: "{{ service_configs }}"
  loop_control:
    loop_var: one_config_definition
  when: service_configs is defined

- name: copy configs templates to remote host
  template:
    src: "{{ provisioner_configs_dir }}/{{ one_config_definition.src_path  | default(service_name + (one_config_definition.path | default(''))) }}"
    dest: "{{ service_config_dir }}/{{ service_name_altered }}/{{ (one_config_definition.dst_path | default(one_config_definition.path | default(one_config_definition.src_path))) }}"
    mode: "{{ '0644' if one_config_definition.permissions is not defined else one_config_definition.permissions }}"
  with_items: "{{ service_configs }}"
  loop_control:
    loop_var: one_config_definition
  when: service_configs is defined
