---
- name: remove secret if it already exists
  become: no
  command: kubectl --namespace {{ k8s_namespace }} delete {{'secret' if (item.type is not defined or item.type=='secret') else 'configmap'}} {{ service_name_altered }}-{{ item.id }}
  ignore_errors: true
  with_items: "{{ service_configs }}"
  when: service_configs is defined

- name: create secret from service config files
  become: no
  command: kubectl --namespace {{ k8s_namespace }} create {{'secret generic' if (item.type is not defined or item.type=='secret') else 'configmap'}}  "{{ service_name_altered }}-{{ item.id }}"  --from-file  "{{ service_config_dir }}/{{ service_name_altered }}/{{ item.dst_path  | default(item.path | default('')) }}"
  with_items: "{{ service_configs }}"
  when: service_configs is defined
