---
- name: remove secrets if it already exists
  command: docker secret rm {{ service_name_altered }}-{{ item.id }}
  ignore_errors: true
  with_items: "{{ service_configs }}"
  when: service_configs is defined

- name: create secrets from service config files
  command: docker secret create {{ service_name_altered }}-{{ item.id }} {{ service_config_dir }}/{{ service_name_altered }}/{{ item.dst_path  | default(item.path) }}
  with_items: "{{ service_configs }}"
  when: service_configs is defined
