swagger: "2.0"
info:
  version: "0.0.1"
  title: Ansible Deploy
host: localhost:10010
basePath: /
#
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /callAnsibleDeploy:
    x-swagger-router-controller: ansible_controller
    get:
      description: Call method that starts ansible deploy
      operationId: callAnsibleDeploy
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/AnsibleRunnerResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /statusCheck:
    x-swagger-router-controller: ansible_controller
    get:
      description: Call method that checks status of ansible deploy
      operationId: callStatusCheck
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/AnsibleStatusResponse'
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"

  /collector/wazuh:
    x-swagger-router-controller: collector
    post:
      description: hook URL for Wazuh alerts
      operationId: createWazuhReport
      parameters:
        - name: data
          in: body
          required: true
          schema:
            $ref: "#/definitions/WazuhAlert"
      responses:
        "204":
          description: Success
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"

  /collector/{source}:
    x-swagger-router-controller: collector
    post:
      description: hook URL for alerts
      operationId: createReport
      parameters:
        - name: source
          in: path
          type: string
          required: true
        - name: data
          in: body
          required: true
          schema:
            type: string
      responses:
        "204":
          description: Success
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"

  /swagger:
    x-swagger-pipe: swagger_raw
definitions:
  AnsibleRunnerResponse:
    required:
      - message
    properties:
      message:
        type: string
  AnsibleStatusResponse:
    required:
      - status
      - output
    properties:
      status: 
        type: string
      output: 
        type: string
  WazuhAlert:
    properties:
      attachments:
        type: array
        items:
          properties:
            pretext:
              type: string
            title:
              type: string
            text:
              type: string
            fields:
              type: array
              items:
                properties:
                  title:
                    type: string
                  value:
                    type: string
                required:
                  - title
                  - value
          required:
            - pretext
            - title
            - text
            - fields
    required:
      - attachments
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
