---
- name: set logger variables when service uses bunyan logger
  set_fact: log_arg="-e BUNYAN_LOG_PREFIX={{ service_name_altered }} -e BUNYAN_LOG_LEVEL={{ service_log_level }}"
  when: service_bunyan_logger is defined and service_bunyan_logger

- name: set logger variables to empty when service doesn't use bunyan logger
  set_fact: log_arg=""
  when: service_bunyan_logger is not defined or not service_bunyan_logger

- name: set environment vars for run command
  set_fact: env_arg="{{ '-e ' ~ service_env_vars | join(' -e ') + ' ' + log_arg }}"
  when: service_env_vars is defined and service_env_vars | length > 0

- name: set environment vars arg to log_arg when service doesn't need custom environment variables
  set_fact: env_arg={{ log_arg }}
  when: service_env_vars is not defined or service_env_vars  | length == 0

- name: Set port argument to empty when service doesn't need exposed ports
  set_fact: port_arg=""
  when: service_ports is not defined or service_ports | length == 0

- name: Set port argument for run command
  set_fact: port_arg="{{ '-p ' ~ service_ports | join(' -p ') }}"
  when: service_ports is defined and service_ports | length > 0

- name: Set sys admin to empty
  set_fact: sys_admin_arg=""
  when: sys_admin is not defined or not sys_admin

- name: Set sys admin if it is
  set_fact: sys_admin_arg="--cap-add SYS_ADMIN "
  when: sys_admin is defined and sys_admin

- name: Set external dns command to empty
  set_fact: external_dns_arg=""
  when: external_dns is not defined or not external_dns

- name: Set external dns command if service requires it
  set_fact: external_dns_arg="--dns 8.8.8.8"
  when: external_dns is defined and external_dns

- name: Set default dns arg
  set_fact: dns_arg="--dns=172.17.0.1 "
  when: main_dns is not defined or not main_dns

- name: Set dns arg
  set_fact: dns_arg="{{ '--dns=' ~ main_dns }}"
  when: main_dns is defined

- name: Set ulimit arg to empty
  set_fact: ulimit_arg=""
  when: service_ulimit is not defined or not service_ulimit

- name: Set ulimit_arg
  set_fact: ulimit_arg="{{ '--ulimit=' ~ service_ulimit }}"
  when: service_ulimit is defined

- name: Set cpus_arg to empty
  set_fact: cpus_arg=""
  when: service_cpus is not defined or not service_cpus

- name: Set cpus_arg
  set_fact: cpus_arg="{{ '--cpus=' ~ service_cpus }}"
  when: service_cpus is defined


- name: Set network arg to empty
  set_fact: network_arg=""
  when: attach_to_network is not defined or not attach_to_network

- name: Set network arg
  set_fact: network_arg="{{ '--network ' ~ docker_network }}"
  when: attach_to_network is defined and attach_to_network

- name: set mounts argument to empty
  set_fact: mount_arg=""
  when: service_mounts is not defined or service_mounts | length == 0

- name: Set mounts arguments if defined
  set_fact: mount_arg="{{ '-v ' ~ service_mounts | join(' -v ') }}"
  when: service_mounts is defined and service_mounts | length > 0

- name: Set mounts arguments using extended syntax if defined
  set_fact: mount_ext_arg="{{ '--mount ' ~ service_mounts_extended | join(' --mount ') }}"
  when: service_mounts_extended is defined and service_mounts_extended | length > 0

- name: set extended mounts argument to empty
  set_fact: mount_ext_arg=""
  when: service_mounts_extended is not defined or service_mounts_extended | length == 0
