---
- name: Set mount config argument to empty
  set_fact: mount_config_arg=""


- name: set mount config argument for configs {{ service_name_altered }}
  set_fact:
    mount_config_arg:
      "{{ mount_config_arg }}\
      -v {{ service_config_dir }}/{{ service_name_altered }}/{{ one_config_definition.dst_path  | default(one_config_definition.path) }}:\
      {{ one_config_definition.dst_path  | default(one_config_definition.path) }}:\
      {{ one_config_definition.mount_mode | default('ro') }}"
  when: service_configs is defined
  with_items: "{{ service_configs }}"
  loop_control:
    loop_var: one_config_definition

- name: set restart policy arg to empty
  set_fact: restart_arg=""

- name: set restart policy arg if service needs it
  set_fact: restart_arg="--restart {{ restart_policy }}"
  when: restart_policy is defined

- name: set max retries if using on-failure restart policy
  set_fact: restart_arg="{{ restart_arg }}:{{ max_retries }}"
  when: restart_policy is defined and restart_policy == 'on-failure' and max_retries is defined

- name: Pull {{ service_image }} image before running
  command: docker pull {{ service_image }}
  when: service_use_local_image is not defined or not service_use_local_image

- name: Set docker service start arguments
  set_fact: >
            start_args="--name {{ service_name_altered }} {{ port_arg }} {{ ulimit_arg }}  {{ cpus_arg }} {{ mount_config_arg }} {{ mount_arg }}
            {{ mount_ext_arg }} {{ sys_admin_arg }} {{ env_arg }} {{ dns_arg }} {{ external_dns_arg }}  {{ network_arg }}
            {{ restart_arg }} -e SERVICE_NAME={{ service_name_altered }} {{ service_image }}"
