---
- name: check if registrator already running
  command: docker inspect registrator
  register: registrator_running
  ignore_errors: true

- name: start registrator
  command: >
           docker run -d -v /var/run/docker.sock:/tmp/docker.sock --name registrator {{ images.registrator }}
           -ip {{ hostvars[inventory_hostname]['public_ip'] }} consul://{{ hostvars[groups['dns-server'][0]]['public_ip'] }}:8500
  when: registrator_running is failed
