---
- hosts: elk
  become: yes
  pre_tasks:
    - import_tasks: "{{ansible_dir}}/globals/vars.yml"
  roles:
    - role: docker-container
      service_name: elastic
      service_type: 'docker'
      service_ports:
        - "{{ports.elasticsearch}}:9200"
      service_image: "{{images.elasticsearch}}:{{versions.elasticsearch}}"
      service_mounts:
        - "{{es_volume}}:/usr/share/elasticsearch/data"
      service_env_vars:
        - "discovery.type=single-node"
