---
- hosts: runtime
  become: yes
  pre_tasks:
    - import_tasks: "{{ansible_dir}}/globals/vars.yml"
    - role: daemon-change
      logstash_ip: "{{ ips.logstash }}"
      lostash_port: "{{ ports.logstash }}"
