---
- name: check if consul already running
  command: docker inspect consul-agent
  register: consul_running
  ignore_errors: true

- name: start consul
  command: >
          docker run -d -p 8301:8301/tcp -p 8301:8301/udp -p 53:8600/udp
          --name consul-agent {{ images.consul }} agent -client 0.0.0.0
          -join={{ hostvars[groups['dns-server'][0]]['public_ip'] }}
          -advertise {{ hostvars[inventory_hostname]['public_ip'] }} -recursor 8.8.8.8
  when: consul_running is failed
