---
- import_tasks: centos.yml
  when: ansible_distribution == 'CentOS'

- import_tasks: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- fail:
    msg: Unsupported operating system, currently supporting CentOS and Ubuntu
  when: ansible_distribution != 'CentOS' and ansible_distribution != 'Ubuntu'

- name: Create a docker group
  group: name=docker

- name: Create directory for local deamon.json
  file:
    path: /etc/docker
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Copy deamon.json
  copy:
    src: ./files/daemon.json
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0644

- name: add curent '{{ ansible_user }}' to docker groups
  user: name={{ ansible_user }} groups=docker append=yes

- name: Reload systemd
  command: systemctl daemon-reload
  when: as_system_service is defined and as_system_service

- name: Enable docker service
  service: name=docker enabled=yes state=started

- name: Registry login
  shell: 'echo "{{ docker_registry_password }}" | docker login --username  {{ docker_registry_user }} --password-stdin  {{ docker_registry }}'
  when: docker_registry is defined and docker_registry_password is defined and docker_registry_user is defined
